### ISSUE TITLE
form_config violates namespacing rules

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#11]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

form_config should really be namespaced rather than /form_config which could conflict with other core classes.

**Comment by danmarsden** [comment]
also - the function addelementclassiconform shouldn't really be hidden at the bottom of that class file - you should drop it in locallib.php (or lib.php) and it should be prefixed with mod_dicomviewer (or just dicomviewer_) to follow our naming rules.

**Comment by salimkanoun** [comment]
Thx, we fixed it
