### ISSUE TITLE
Please test your plugin with debugging level set to "developer" with display errors = on

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#12]
under admin> developer > debugging, please set the level to developer with display errors = on and test your plugin - it should not display any php or moodle debuging warnings. I spotted a few places in your code where I would expect to see warnings displayed - please note these are blockers for approval.

**Comment by salimkanoun** [comment]
Thanks, we run it in debugging mode and fix warnings
