### ISSUE TITLE
check version of thirdpartylibs

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#13]
the stoneviewer versino seems semi recent, but the ohif one seems like it's been through quite a few updates since the version mentioned in your thirdpartylibs.xml file - it would be good for you to check to see if there are newer versions that fix any issues (particularly any that have security issues in their dependencies)

**Comment by salimkanoun** [comment]
thanks for feedback, we updated both packages
