### ISSUE TITLE
debugging message on install

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#18]
XMLDB has detected one TEXT/BINARY column (studyinstance) with some DEFAULT defined. This type of columns cannot have any default value. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed.
line 1696 of /lib/datalib.php: call to debugging()
line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
line 261 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
line 359 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()
line 543 of /lib/xmldb/xmldb_table.php: call to xmldb_field->arr2xmldb_field()
line 276 of /lib/xmldb/xmldb_structure.php: call to xmldb_table->arr2xmldb_table()
line 172 of /lib/xmldb/xmldb_file.php: call to xmldb_structure->arr2xmldb_structure()
line 153 of /lib/xmldb/xmldb_file.php: call to xmldb_file->arr2xmldb_structure()
line 349 of /lib/ddl/database_manager.php: call to xmldb_file->loadXMLStructure()
line 370 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
line 847 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
line 582 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
line 721 of /admin/index.php: call to upgrade_noncore()

**Comment by salimkanoun** [comment]
Yes, we removed the default value.
