### ISSUE TITLE
configuration stored in lang string?

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#20]
https://github.com/salimkanoun/moodle-mod_dicomviewer/blob/main/lang/en/dicomviewer.php#L51-L52

Those lines don't look like language strings - they should probably be stored somewhere else...

When putting something in the language file - think "how would someone translate this to German?" - if it's exactly the same, or is not a text string that is translatable it should probably be somewhere else. I suspect those 2 lines might need to be admin settings?

**Comment by salimkanoun** [comment]
Correct ! We corrected this ! Thanks !
