### ISSUE TITLE
How to config IIS to reverse proxy Orthanc?

### ISSUE THREAD

**Issue by xuyuanfu67** [salimkanoun/moodle-mod_dicomviewer#25]
Hello! The dicomviewer pluging was install correctly in my moodle,please help me: how to config IIS to reverse proxy Orthanc?
This is my web.config in IIS:
![image](https://user-images.githubusercontent.com/128232112/233417669-1310b5a1-8e6f-4e1c-bb34-42462168b61c.png)

But it is not effective,this infomation is showed when I use ohif viewer:
![image](https://user-images.githubusercontent.com/128232112/233417798-2e071251-2098-4942-b7b9-ae3edc7d1e0b.png)

Please help me to solve this problem,thank you!!!

**Comment by salimkanoun** [comment]
Hi  you should reverse proxy Orthanc dicom web api not OHIF. 

OHIF has a example reverse proxy for Orthanc here : https://github.com/OHIF/Viewers/blob/2f443fa2efa223ac0fcdf238eee834c6a4ee3fc1/.docker/Nginx-Orthanc/config/nginx.conf

**Comment by xuyuanfu67** [comment]
Thank for your help very much!
But this is nginx.conf,not IIS config.Because I was install Orthanc in my local server,so I want to reverse proxy Orthanc dicom web,then visit dicom image form orthanc use dicomviewer pluging in moodle.Ohif viewer can not regular work!
Can you give me much suggestion?Thank you!

**Comment by xuyuanfu67** [comment]
By the way,how to use dicomviewer\config-ohif\init-service-worker.js??? Thank!
