### ISSUE TITLE
How to config and use Moodle-mod_dicomviewer?

### ISSUE THREAD

**Issue by xuyuanfu67** [salimkanoun/moodle-mod_dicomviewer#26]
Hello,thank for your help very much!
Can you tell me how to config and use moodle-mod_dicomviewer?Do I still need to install ohif viewer or stone viewer independently?

**Comment by salimkanoun** [comment]
Hi sorry i don't have time to provide support, the sources are fully available, OHIF is a frontend viewer shipped in the moodle distribution but you need to install the dicom web server
