### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by xuyuanfu67** [salimkanoun/moodle-mod_dicomviewer#27]
Thank you very much！
I had already install Orthanc dicom web server and moodle-mod_dicomviewer plugin,but I don't know how to config IIS web server to reverse proxy orthanc. I tried many times but failed, and nothing was displayed through the plugin，display 404 error。
Please try your best to help me！

**Comment by salimkanoun** [comment]
I don't know neither about IIS, i sent you a reverse proxy configuration in ngnix, just look at IIS documentation how to do the equivalent reverse proxy (that's should be hard)
