### ISSUE TITLE
Missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#5]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
I still can't see this one in your repository? - did you add it correctly?

here's an example thirdpartylibs.xml file from one of our plugins that shows you an example of what I'm looking for here:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/thirdpartylibs.xml

**Comment by exploff** [comment]
Yes it's my fault, it was in another folder, I remounted it to the root.
It must be good now.

**Comment by exploff** [comment]
> 
> 
> I still can't see this one in your repository? - did you add it correctly?
> 
> here's an example thirdpartylibs.xml file from one of our plugins that shows you an example of what I'm looking for here:
> https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/thirdpartylibs.xml

**Comment by danmarsden** [comment]
it looks ok in the repo here, but the version you uploaded to the plugins db doesn't show it in the root so the plugin validation process is showing more errors than we expect. Can you please re-package and upload a version to the plugins db that includes the thirdpartylibs.xml file?

**Comment by salimkanoun** [comment]
We are going to repackage and submit the 1.1.0 version, thx !
