### ISSUE TITLE
consider adding github actions support for checking code compliance

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#8]
when you have resolved #6 

Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/main/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by danmarsden** [comment]
note - make sure you've got the thirdpartylibs.xml file in there first too, because it will ignore the 3rd party external libs when running these tests.

**Comment by exploff** [comment]
Thank you for your feedback, we have modified the various problems as well as added the CI. Hoping not to have forgotten anything.
We added and validated the CI.
Hoping not to have forgotten anything.
