### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [salimkanoun/moodle-mod_dicomviewer#9]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin doesn't appear to store any user data so you should be able to implement the simple null provider class.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Note - this is not a blocker for approval in the plugins db.

**Comment by salimkanoun** [comment]
Yes we add the null provider class as we don't store any personal information
